name: Kevin Purdy
markdown: redcarpet
kramdown:
    input: GFM
markdown: kramdown
pygments: false
base_url: http://thepurdman.com
description: Kevin Purdy, the writer who lives in Washington, D.C.
permalink: /:title/
highlighter: rouge
