name: Kevin Purdy
markdown: redcarpet
kramdown:
    input: GFM
markdown: kramdown
pygments: false
base_url: http://thepurdman.com
description: "Kevin Purdy's personal site"
permalink: /:title/
highlighter: rouge
